# Molecule managed                                                                
{% raw %}                                                                                  
{% if item.registry is defined %}                                                 
FROM {{ item.registry.url }}/{{ item.image }}                                     
{% else %}                                                                        
FROM {{ item.image }}                                                             
{% endif %}                                                                       

ENV container docker

# Alpine
RUN if [ $(command -v apk) ]; then \
    apk update && \
    apk add --no-cache python sudo bash ca-certificates; fi

# Archlinux
RUN if [ $(command -v pacman) ]; then \
    pacman --sync --noconfirm --refresh python bash sudo grep; fi

# Debian
RUN if [ $(command -v apt-get) ]; then \
    apt-get update && \
    apt-get install -y python sudo bash ca-certificates && \
    apt-get clean; fi

# Fedora
RUN if [ $(command -v dnf) ]; then \
    dnf makecache && \
    dnf --assumeyes install python sudo python-devel python*-dnf bash && \
    dnf clean all; fi

# Gentoo
RUN if [ $(command -v emerge) ]; then \
    emerge --ask n =dev-lang/python-2\* gentoolkit; fi

# RedHat/CentOS
RUN if [ $(command -v yum) ]; then \
    yum makecache fast && \
    yum install -y python sudo yum-plugin-ovl bash && \
    sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; fi

# SuSE
RUN if [ $(command -v zypper) ]; then \
    zypper refresh && \
    zypper install -y python sudo bash python-xml && \
    zypper clean -a; fi